# Site settings
title: Wahyu Rahmaniar 
#twitter_username: wahyurahmaniar
name: Wahyu Rahmaniar

# Build settings
#markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: Blog
   url: http://technologination.blogspot.com/
 - title: GitHub
   url: https://github.com/wahyurahmaniar  
 - title: LinkedIn
   url: https://www.linkedin.com/in/wahyu-rahmaniar-22041987/
 - title: Facebook
   url: https://www.facebook.com/wahyu.rahmaniar
 - title: Twitter
   url: https://twitter.com/WahyuRahmaniar
 - title: Google Scholar
   url: https://scholar.google.com/citations?user=AeJN-sYAAAAJ&hl=en
#  - title: Scopus
#    url: https://www.scopus.com/authid/detail.uri?authorId=56982984800
 - title: ResearchGate
   url: https://www.researchgate.net/profile/Qazi-Mazhar

#Any buzzword skills you want to include
skills:
 
 - LaTeX
 - C/C++
 - MATLAB
 - OpenCV
 - Python
 - PyTorch
 - Tensorflow
 


#Blogfeed is optional - including this will add JS to call the feed and populate blog list
# blogfeed: Previous Research

#Work experience is required
#roles:
# - title: CTO
#   start: 2017
#   end: Ongoing
#   employer: Basement Crowd
#   description: Legaltech startup producing a range of innovative legal products. Products include <a href="https://www.juriosity.com" taget="_blank">Juriosity</a>, <a href="https://www.fromcounsel.com" taget="_blank">FromCounsel</a>, <a href="https://www.sparqa.com" taget="_blank">Sparqa</a>.

#Education is required
education:
 - level: Doctor of Philosophy (Ph.D.)
   date: 2021
   dept: Electronics and Computer Engineering
   subject: (Computer Vision and Artificial Intelligence)
   school: National Taiwan University of Science and Technology
 - level: ( MS in Electrical Enginieering)
   date: 2016
   dept: Electrical Engineering
   subject: (Image Processing)
   school: National University of Sciences and Technology
 - level: Bachelor of Engineering 
   date: 2014
   dept: Telecommunication Engineering
   subject: Signal Processing and Image Processing
   school: Universitas of Engineering and Technology Peshawar

#This section is optional - embeds slideshows from speakerdeck
# to get the speakerdeck ID copy the embed code and look for the data-it attribute
# speakerdeck:
#    talks:
#     - title: Menggapai Mimpi di Kancah Internasional
#       host: Universitas Internasional Semen Indonesia (UISI)
#       date: July 4, 2020
#    talks2:
#     - title: Artificial Intelligence Applications in Real-Life
#       host: Sekolah Tinggi Teknologi Bandung (STTB)
#       date: July 10, 2021
#    talks3:
#     - title: When Remote Sensing Meets Artificial Intelligence 
#       host: Universitas Negeri Makasar (UNM)
#       date: December 4, 2021

#List of interesting Github repo/projects to include - optional
#github:
# - wahyurahmaniar/wahyurahmaniar.github.io

#This section is optional (as is the image link below)
# coursera: Awards

#Stackoverflow flair is optional
# stackoverflow: Resume
#   profileurl: https://stackoverflow.com/users/258813/rhinds
#   flairimageurl: https://stackoverflow.com/users/flair/258813.png

intro: |
  <p style="font-size:15px;">
  Currently I'm a Postdoctoral Researcher at National Taipei University of Technology (NTUT), Taiwan. I received the B.S. degree in Telecommunication Engineeirng from University of Engineering and Technology Peshawar, Pakistan in 2014 and MS from National Unvoersity of Sciences and Technology Islamabad, Pakistan. I completed my Ph.D. degree in Electronics and Computer Engineering from National CTaiwan University of Science and Technology (NTUST), Taiwan, in 2021. 
  My research interests are in the areas of robotics, computer vision, image processing, and AI. <br/><br/>
  
  The research I conducted in the field of computer vision and image processing, including AI. I used C++ or Python programming on Windows or Linux operating systems. Overall, I have at least 10 years experience in programming. And for the AI field, I have studied it since I took a Ph.D. degree until now for about 7 years.
  For intelligent systems, I focus more on developing algorithms or frameworks that can run systems in the real-time in the actual environment. Besides, I also understand well enough the theory and mathematics for these systems, including machine learning and deep learning. One of my interests in AI research is that I want to create my own network or method. 
  I have also been a reviewer in several journals, such as Circuit World, Sensor Review, Journal of Robotics and Control, Journal of Electronic Imaging, Sensors (MDPI), BDCC (MDPI), and Scientific Reports (Nature). <br/><br/>
  
  </p>
  <p style="color:blue "align="right">~Qazi~</p>

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   <p style="font-size:14px;"><strong>Year</strong>: Feb 2022 - now <br/>
   <strong>Office</strong>: National Taipei University of Technology (NTUT), Taiwan<br/>
   <strong>Position</strong>: Postdoctoral Researcher <br/>
   <strong>Subject</strong>:computer vision, image processing, artificial intelligence <br/>
   </p>

   <p style="font-size:14px;"><strong>Year</strong>: Jan 2019 - Dec 2020 <br/>
   <strong>Office</strong>: Industrial Technology Research Institute, Hsinchu, Taiwan <br/>
   <strong>Position</strong>: Projects <br/>
   <strong>Subject</strong>: computer vision, image processing, artificial intelligence <br/>
   </p
   
